[tool.poetry]
name = "app"
version = "0.0.1"
description = "Ultimate FastAPI Tutorial Part 2"
authors = ["ChristopherGS"]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "~0.21.1"
fastapi = "~0.95.0"
python-multipart = "~0.0.6"
pydantic = {extras = ["email"], version = "~1.10.7"}